// This file is autogenerated by the hyperdb compiler
/* eslint-disable camelcase */

import { IndexEncoder, c } from 'hyperdb/runtime'
import { version, getEncoding, setVersion } from './messages.js'

// '@doctor/checklist' collection key
const collection0_key = new IndexEncoder([IndexEncoder.STRING], { prefix: 0 })

function collection0_indexify(record) {
  const a = record.key
  return a === undefined ? [] : [a]
}

// '@doctor/checklist' value encoding
const collection0_enc = getEncoding('@doctor/checklist/hyperdb#0')

// '@doctor/checklist' reconstruction function
function collection0_reconstruct(version, keyBuf, valueBuf) {
  const key = collection0_key.decode(keyBuf)
  setVersion(version)
  const record = c.decode(collection0_enc, valueBuf)
  record.key = key[0]
  return record
}
// '@doctor/checklist' key reconstruction function
function collection0_reconstruct_key(keyBuf) {
  const key = collection0_key.decode(keyBuf)
  return {
    key: key[0]
  }
}

// '@doctor/checklist'
const collection0 = {
  name: '@doctor/checklist',
  id: 0,
  encodeKey(record) {
    const key = [record.key]
    return collection0_key.encode(key)
  },
  encodeKeyRange({ gt, lt, gte, lte } = {}) {
    return collection0_key.encodeRange({
      gt: gt ? collection0_indexify(gt) : null,
      lt: lt ? collection0_indexify(lt) : null,
      gte: gte ? collection0_indexify(gte) : null,
      lte: lte ? collection0_indexify(lte) : null
    })
  },
  encodeValue(version, record) {
    setVersion(version)
    return c.encode(collection0_enc, record)
  },
  trigger: null,
  reconstruct: collection0_reconstruct,
  reconstructKey: collection0_reconstruct_key,
  indexes: []
}

const collections = [collection0]

const indexes = []

export default {
  version,
  collections,
  indexes,
  resolveCollection,
  resolveIndex
}

function resolveCollection(name) {
  switch (name) {
    case '@doctor/checklist':
      return collection0
    default:
      return null
  }
}

function resolveIndex(name) {
  switch (name) {
    default:
      return null
  }
}
